// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package protobuf;

public interface MensagemOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serializacao.Mensagem)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.serializacao.PingMsg pingMsg = 1;</code>
   * @return Whether the pingMsg field is set.
   */
  boolean hasPingMsg();
  /**
   * <code>.serializacao.PingMsg pingMsg = 1;</code>
   * @return The pingMsg.
   */
  PingMsg getPingMsg();
  /**
   * <code>.serializacao.PingMsg pingMsg = 1;</code>
   */
  PingMsgOrBuilder getPingMsgOrBuilder();

  /**
   * <code>.serializacao.PongMsg pongMsg = 2;</code>
   * @return Whether the pongMsg field is set.
   */
  boolean hasPongMsg();
  /**
   * <code>.serializacao.PongMsg pongMsg = 2;</code>
   * @return The pongMsg.
   */
  PongMsg getPongMsg();
  /**
   * <code>.serializacao.PongMsg pongMsg = 2;</code>
   */
  PongMsgOrBuilder getPongMsgOrBuilder();

  /**
   * <code>.serializacao.Iniciar init = 3;</code>
   * @return Whether the init field is set.
   */
  boolean hasInit();
  /**
   * <code>.serializacao.Iniciar init = 3;</code>
   * @return The init.
   */
  Iniciar getInit();
  /**
   * <code>.serializacao.Iniciar init = 3;</code>
   */
  IniciarOrBuilder getInitOrBuilder();
}
