// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package protobuf;

/**
 * Protobuf type {@code serializacao.Mensagem}
 */
public  final class Mensagem extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:serializacao.Mensagem)
    MensagemOrBuilder {
private static final long serialVersionUID = 0L;
  // Use Mensagem.newBuilder() to construct.
  private Mensagem(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private Mensagem() {
  }

  @java.lang.Override
  @SuppressWarnings({"unused"})
  protected java.lang.Object newInstance(
      UnusedPrivateParameter unused) {
    return new Mensagem();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private Mensagem(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          case 10: {
            PingMsg.Builder subBuilder = null;
            if (pingMsg_ != null) {
              subBuilder = pingMsg_.toBuilder();
            }
            pingMsg_ = input.readMessage(PingMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pingMsg_);
              pingMsg_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            PongMsg.Builder subBuilder = null;
            if (pongMsg_ != null) {
              subBuilder = pongMsg_.toBuilder();
            }
            pongMsg_ = input.readMessage(PongMsg.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(pongMsg_);
              pongMsg_ = subBuilder.buildPartial();
            }

            break;
          }
          default: {
            if (!parseUnknownField(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return MsgProto.internal_static_serializacao_Mensagem_descriptor;
  }

  @java.lang.Override
  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return MsgProto.internal_static_serializacao_Mensagem_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            Mensagem.class, Mensagem.Builder.class);
  }

  public static final int PINGMSG_FIELD_NUMBER = 1;
  private PingMsg pingMsg_;
  /**
   * <code>.serializacao.PingMsg pingMsg = 1;</code>
   * @return Whether the pingMsg field is set.
   */
  public boolean hasPingMsg() {
    return pingMsg_ != null;
  }
  /**
   * <code>.serializacao.PingMsg pingMsg = 1;</code>
   * @return The pingMsg.
   */
  public PingMsg getPingMsg() {
    return pingMsg_ == null ? PingMsg.getDefaultInstance() : pingMsg_;
  }
  /**
   * <code>.serializacao.PingMsg pingMsg = 1;</code>
   */
  public PingMsgOrBuilder getPingMsgOrBuilder() {
    return getPingMsg();
  }

  public static final int PONGMSG_FIELD_NUMBER = 2;
  private PongMsg pongMsg_;
  /**
   * <code>.serializacao.PongMsg pongMsg = 2;</code>
   * @return Whether the pongMsg field is set.
   */
  public boolean hasPongMsg() {
    return pongMsg_ != null;
  }
  /**
   * <code>.serializacao.PongMsg pongMsg = 2;</code>
   * @return The pongMsg.
   */
  public PongMsg getPongMsg() {
    return pongMsg_ == null ? PongMsg.getDefaultInstance() : pongMsg_;
  }
  /**
   * <code>.serializacao.PongMsg pongMsg = 2;</code>
   */
  public PongMsgOrBuilder getPongMsgOrBuilder() {
    return getPongMsg();
  }

  private byte memoizedIsInitialized = -1;
  @java.lang.Override
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  @java.lang.Override
  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (pingMsg_ != null) {
      output.writeMessage(1, getPingMsg());
    }
    if (pongMsg_ != null) {
      output.writeMessage(2, getPongMsg());
    }
    unknownFields.writeTo(output);
  }

  @java.lang.Override
  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (pingMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getPingMsg());
    }
    if (pongMsg_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getPongMsg());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof Mensagem)) {
      return super.equals(obj);
    }
    Mensagem other = (Mensagem) obj;

    if (hasPingMsg() != other.hasPingMsg()) return false;
    if (hasPingMsg()) {
      if (!getPingMsg()
          .equals(other.getPingMsg())) return false;
    }
    if (hasPongMsg() != other.hasPongMsg()) return false;
    if (hasPongMsg()) {
      if (!getPongMsg()
          .equals(other.getPongMsg())) return false;
    }
    if (!unknownFields.equals(other.unknownFields)) return false;
    return true;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasPingMsg()) {
      hash = (37 * hash) + PINGMSG_FIELD_NUMBER;
      hash = (53 * hash) + getPingMsg().hashCode();
    }
    if (hasPongMsg()) {
      hash = (37 * hash) + PONGMSG_FIELD_NUMBER;
      hash = (53 * hash) + getPongMsg().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static Mensagem parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Mensagem parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Mensagem parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Mensagem parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Mensagem parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static Mensagem parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static Mensagem parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Mensagem parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static Mensagem parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static Mensagem parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static Mensagem parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static Mensagem parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  @java.lang.Override
  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(Mensagem prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  @java.lang.Override
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code serializacao.Mensagem}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:serializacao.Mensagem)
          MensagemOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return MsgProto.internal_static_serializacao_Mensagem_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return MsgProto.internal_static_serializacao_Mensagem_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              Mensagem.class, Mensagem.Builder.class);
    }

    // Construct using protobuf.Mensagem.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    @java.lang.Override
    public Builder clear() {
      super.clear();
      if (pingMsgBuilder_ == null) {
        pingMsg_ = null;
      } else {
        pingMsg_ = null;
        pingMsgBuilder_ = null;
      }
      if (pongMsgBuilder_ == null) {
        pongMsg_ = null;
      } else {
        pongMsg_ = null;
        pongMsgBuilder_ = null;
      }
      return this;
    }

    @java.lang.Override
    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return MsgProto.internal_static_serializacao_Mensagem_descriptor;
    }

    @java.lang.Override
    public Mensagem getDefaultInstanceForType() {
      return Mensagem.getDefaultInstance();
    }

    @java.lang.Override
    public Mensagem build() {
      Mensagem result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    @java.lang.Override
    public Mensagem buildPartial() {
      Mensagem result = new Mensagem(this);
      if (pingMsgBuilder_ == null) {
        result.pingMsg_ = pingMsg_;
      } else {
        result.pingMsg_ = pingMsgBuilder_.build();
      }
      if (pongMsgBuilder_ == null) {
        result.pongMsg_ = pongMsg_;
      } else {
        result.pongMsg_ = pongMsgBuilder_.build();
      }
      onBuilt();
      return result;
    }

    @java.lang.Override
    public Builder clone() {
      return super.clone();
    }
    @java.lang.Override
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.setField(field, value);
    }
    @java.lang.Override
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return super.clearField(field);
    }
    @java.lang.Override
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return super.clearOneof(oneof);
    }
    @java.lang.Override
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return super.setRepeatedField(field, index, value);
    }
    @java.lang.Override
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return super.addRepeatedField(field, value);
    }
    @java.lang.Override
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof Mensagem) {
        return mergeFrom((Mensagem)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(Mensagem other) {
      if (other == Mensagem.getDefaultInstance()) return this;
      if (other.hasPingMsg()) {
        mergePingMsg(other.getPingMsg());
      }
      if (other.hasPongMsg()) {
        mergePongMsg(other.getPongMsg());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    @java.lang.Override
    public final boolean isInitialized() {
      return true;
    }

    @java.lang.Override
    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Mensagem parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (Mensagem) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private PingMsg pingMsg_;
    private com.google.protobuf.SingleFieldBuilderV3<
            PingMsg, PingMsg.Builder, PingMsgOrBuilder> pingMsgBuilder_;
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     * @return Whether the pingMsg field is set.
     */
    public boolean hasPingMsg() {
      return pingMsgBuilder_ != null || pingMsg_ != null;
    }
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     * @return The pingMsg.
     */
    public PingMsg getPingMsg() {
      if (pingMsgBuilder_ == null) {
        return pingMsg_ == null ? PingMsg.getDefaultInstance() : pingMsg_;
      } else {
        return pingMsgBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     */
    public Builder setPingMsg(PingMsg value) {
      if (pingMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pingMsg_ = value;
        onChanged();
      } else {
        pingMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     */
    public Builder setPingMsg(
        PingMsg.Builder builderForValue) {
      if (pingMsgBuilder_ == null) {
        pingMsg_ = builderForValue.build();
        onChanged();
      } else {
        pingMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     */
    public Builder mergePingMsg(PingMsg value) {
      if (pingMsgBuilder_ == null) {
        if (pingMsg_ != null) {
          pingMsg_ =
            PingMsg.newBuilder(pingMsg_).mergeFrom(value).buildPartial();
        } else {
          pingMsg_ = value;
        }
        onChanged();
      } else {
        pingMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     */
    public Builder clearPingMsg() {
      if (pingMsgBuilder_ == null) {
        pingMsg_ = null;
        onChanged();
      } else {
        pingMsg_ = null;
        pingMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     */
    public PingMsg.Builder getPingMsgBuilder() {
      
      onChanged();
      return getPingMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     */
    public PingMsgOrBuilder getPingMsgOrBuilder() {
      if (pingMsgBuilder_ != null) {
        return pingMsgBuilder_.getMessageOrBuilder();
      } else {
        return pingMsg_ == null ?
            PingMsg.getDefaultInstance() : pingMsg_;
      }
    }
    /**
     * <code>.serializacao.PingMsg pingMsg = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            PingMsg, PingMsg.Builder, PingMsgOrBuilder>
        getPingMsgFieldBuilder() {
      if (pingMsgBuilder_ == null) {
        pingMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                PingMsg, PingMsg.Builder, PingMsgOrBuilder>(
                getPingMsg(),
                getParentForChildren(),
                isClean());
        pingMsg_ = null;
      }
      return pingMsgBuilder_;
    }

    private PongMsg pongMsg_;
    private com.google.protobuf.SingleFieldBuilderV3<
            PongMsg, PongMsg.Builder, PongMsgOrBuilder> pongMsgBuilder_;
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     * @return Whether the pongMsg field is set.
     */
    public boolean hasPongMsg() {
      return pongMsgBuilder_ != null || pongMsg_ != null;
    }
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     * @return The pongMsg.
     */
    public PongMsg getPongMsg() {
      if (pongMsgBuilder_ == null) {
        return pongMsg_ == null ? PongMsg.getDefaultInstance() : pongMsg_;
      } else {
        return pongMsgBuilder_.getMessage();
      }
    }
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     */
    public Builder setPongMsg(PongMsg value) {
      if (pongMsgBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        pongMsg_ = value;
        onChanged();
      } else {
        pongMsgBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     */
    public Builder setPongMsg(
        PongMsg.Builder builderForValue) {
      if (pongMsgBuilder_ == null) {
        pongMsg_ = builderForValue.build();
        onChanged();
      } else {
        pongMsgBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     */
    public Builder mergePongMsg(PongMsg value) {
      if (pongMsgBuilder_ == null) {
        if (pongMsg_ != null) {
          pongMsg_ =
            PongMsg.newBuilder(pongMsg_).mergeFrom(value).buildPartial();
        } else {
          pongMsg_ = value;
        }
        onChanged();
      } else {
        pongMsgBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     */
    public Builder clearPongMsg() {
      if (pongMsgBuilder_ == null) {
        pongMsg_ = null;
        onChanged();
      } else {
        pongMsg_ = null;
        pongMsgBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     */
    public PongMsg.Builder getPongMsgBuilder() {
      
      onChanged();
      return getPongMsgFieldBuilder().getBuilder();
    }
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     */
    public PongMsgOrBuilder getPongMsgOrBuilder() {
      if (pongMsgBuilder_ != null) {
        return pongMsgBuilder_.getMessageOrBuilder();
      } else {
        return pongMsg_ == null ?
            PongMsg.getDefaultInstance() : pongMsg_;
      }
    }
    /**
     * <code>.serializacao.PongMsg pongMsg = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
            PongMsg, PongMsg.Builder, PongMsgOrBuilder>
        getPongMsgFieldBuilder() {
      if (pongMsgBuilder_ == null) {
        pongMsgBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
                PongMsg, PongMsg.Builder, PongMsgOrBuilder>(
                getPongMsg(),
                getParentForChildren(),
                isClean());
        pongMsg_ = null;
      }
      return pongMsgBuilder_;
    }
    @java.lang.Override
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFields(unknownFields);
    }

    @java.lang.Override
    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:serializacao.Mensagem)
  }

  // @@protoc_insertion_point(class_scope:serializacao.Mensagem)
  private static final Mensagem DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Mensagem();
  }

  public static Mensagem getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<Mensagem>
      PARSER = new com.google.protobuf.AbstractParser<Mensagem>() {
    @java.lang.Override
    public Mensagem parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new Mensagem(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<Mensagem> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<Mensagem> getParserForType() {
    return PARSER;
  }

  @java.lang.Override
  public Mensagem getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

