// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package protobuf;

public final class MsgProto {
  private MsgProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serializacao_PingMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serializacao_PingMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serializacao_PongMsg_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serializacao_PongMsg_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_serializacao_Mensagem_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_serializacao_Mensagem_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\016MsgProto.proto\022\014serializacao\"*\n\007PingMs" +
      "g\022\020\n\010mensagem\030\001 \001(\t\022\r\n\005nivel\030\002 \001(\005\"*\n\007Po" +
      "ngMsg\022\020\n\010mensagem\030\001 \001(\t\022\r\n\005nivel\030\002 \001(\005\"Z" +
      "\n\010Mensagem\022&\n\007pingMsg\030\001 \001(\0132\025.serializac" +
      "ao.PingMsg\022&\n\007pongMsg\030\002 \001(\0132\025.serializac" +
      "ao.PongMsgB\022\n\004akkaB\010MsgProtoP\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_serializacao_PingMsg_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_serializacao_PingMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serializacao_PingMsg_descriptor,
        new java.lang.String[] { "Mensagem", "Nivel", });
    internal_static_serializacao_PongMsg_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_serializacao_PongMsg_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serializacao_PongMsg_descriptor,
        new java.lang.String[] { "Mensagem", "Nivel", });
    internal_static_serializacao_Mensagem_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_serializacao_Mensagem_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_serializacao_Mensagem_descriptor,
        new java.lang.String[] { "PingMsg", "PongMsg", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
