// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: MsgProto.proto

package protobuf;

public interface PongMsgOrBuilder extends
    // @@protoc_insertion_point(interface_extends:serializacao.PongMsg)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string mensagem = 1;</code>
   * @return The mensagem.
   */
  java.lang.String getMensagem();
  /**
   * <code>string mensagem = 1;</code>
   * @return The bytes for mensagem.
   */
  com.google.protobuf.ByteString
      getMensagemBytes();
}
